### PR TITLE
Throw errors that arise from spawning processes in create-project

### LINKED ISSUE #895: create-project doesn't detect errors during yarn install
The following `create-project` run reported success, however the output seen thanks to `--debug` showed the `yarn install` command run by it, had actually failed. This resulted in a project that had no `devDependencies` in `package.json` and was not usable.

Presumably create-project isn't catching the non-zero exit code of yarn (on Windows at least):

```
src $ create-project --registry http://localhost:4873/ test-project --debug
                          _          _
      _ __    ___  _   _ | |_  _ __ (_) _ __    ___
     | '_ \  / _ \| | | || __|| '__|| || '_ \  / _ \
     | | | ||  __/| |_| || |_ | |   | || | | || (_) |
     |_| |_| \___| \__,_| \__||_|   |_||_| |_| \___/

Welcome to Neutrino! 👋
To help you create your new project, I am going to ask you a few questions.

? 🤔  First up, what would you like to create? A web or Node.js application
? 🤔  Next, what kind of application would you like to create? Node.js
? 🤔  Would you like to add a test runner to your project? Mocha
? 🤔  Would you like to add linting to your project? Airbnb style rules

👌  Looks like I have all the info I need. Give me a moment while I create your project!

yarn init v1.6.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.

success Saved package.json
Done in 0.05s.
   create test-project\package.json
   create test-project\.neutrinorc.js
   create test-project\webpack.config.js
   create test-project\src\app.js
   create test-project\src\index.js
   create test-project\mocha.config.js
   create test-project\test\simple_test.js
   create test-project\.eslintrc.js

⏳  Installing devDependencies: @neutrinojs/node, neutrino, webpack, webpack-cli, @neutrinojs/mocha, mocha, @neutrinojs/airbnb-base, eslint
yarn add v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@babel/helper-builder-binary-assignment-operator-visitor@7.0.0-beta.47" required by "@babel/plugin-transform-exponentiation-operator@7.0.0-beta.47" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
⏳  Performing one-time lint

Hooray, I successfully created your project!

I have added a few yarn scripts to help you get started:
  • To build your project run:  yarn build
  • To start your project locally run:  yarn start
  • To execute tests run:  yarn test
  • To lint your project manually run:  yarn lint
    You can also fix some linting problems with:  yarn lint --fix

Now change your directory to the following to get started:
  cd test-project

❤️  Neutrino

src $ cd test-project/
test-project $ yarn start
yarn run v1.6.0
$ webpack --watch --mode development
'webpack' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by eliperelman**
Fixes #895.

This PR doesn't attempt to know why an error occurs, but it should at least make them visible should an operation fail during create-project. According to the yeoman docs, `spawnCommandSync` returns an instance of cross-spawn `sync`, which wraps Node's child_process `spawnSync`.

http://yeoman.io/generator/actions_spawn-command.js.html
https://www.npmjs.com/package/cross-spawn
https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options

The `error` property of the result object is either `null` or an `Error` instance, so we just throw it if it exists.

### CODE REVIEW

File: packages/create-project/commands/init/index.js [hunk 1]
```diff
@@ -114,11 +114,15 @@ module.exports = class Project extends Generator {
 
     ensureDirSync(this.options.directory);
 
-    this.spawnCommandSync(installer, ['init', '--yes'], {
+    const { error } = this.spawnCommandSync(installer, ['init', '--yes'], {
```
Comment (edmorley) [inline packages/create-project/commands/init/index.js]: Should we factor this out to another function?

**Comment by eliperelman** [comment]
Let me see if I can replicate using your non-existent registry trick.

**Comment by eliperelman** [comment]
@edmorley ok, I think I have it working now.

**Comment by edmorley** [comment]
Travis is failing - strangely these no error message. Is the `this.log.error()` output being eaten perhaps? (Either in general, or by ava?)

File: packages/create-project/commands/init/index.js [hunk 2]
```diff
@@ -29,6 +29,20 @@ module.exports = class Project extends Generator {
...
   }
 
+  _spawnSync(...args) {
+    const result = this.spawnCommandSync(...args);
+
+    if (result.error || result.status !== 0) {
+      const command = [args[0], ...args[1]].join(' ');
+
+      removeSync(this.options.directory);
+      this.log.error(result.error || new Error(`The command "${command}" exited unsuccessfully.`));
```
Comment (edmorley) [inline packages/create-project/commands/init/index.js]: Unless I use `--debug`, there is no indication of what actually went wrong, since the yarn stdout/stderr is never shown. I think we should also either:
1. Capture stdout/stderr and dump if there was an error
2. Tweak this error message to suggest using `--debug` to find out more
