### PR TITLE
Vue: Allow css modules to co-exist with global styles

### LINKED ISSUE #1243: vue/v9: css modules cannot co-exist with global styles (could in v8)
In v8, it was possible to have vue use css modules, but have co-existing global (non-module) styles.

With the same config in v9, this doesn't work:
```
Module parse failed: Unexpected token (19:0)
You may need an appropriate loader to handle this file type.
```

Working v8 example: https://github.com/timkelty/vue-scss/tree/v8-working
Broken v8 example: https://github.com/timkelty/vue-scss/tree/v9-broken

You can still achieve this in v9, but have to do thing differently:

1. set `modulesTest` equal to `test` (https://github.com/neutrinojs/neutrino/pull/1242 should help with that)
2. use `:global` in your css where you want global (non-module) styles.

-----

If using modules everywhere and requiring `:global` is the only way to do it in v9, that's fine, but it should probably be noted somewhere, as you could do it in v8. A the very least I think we should merge in https://github.com/neutrinojs/neutrino/pull/1242 so you don't have to set both `test` and `modulesTest`

### PR DESCRIPTION
**Pull request by timkelty**
Fixes #1243 

This converts the style rule to a oneOf, to allow for both global and module styes. The `oneOf` approach was cribbed from https://github.com/vuejs/vue-cli/blob/b559005ce64dc801c280e38194f28dd583292095/packages/%40vue/cli-service/lib/config/css.js#L72

> I'm also wondering if restructuring the style and style-modules rule created by style-loader into oneofs might make things easier to deal with? Wouldn't have to worry about multiple applied rules and excluding things, etc.
- https://github.com/neutrinojs/neutrino/issues/1243#issuecomment-450875429:

### CODE REVIEW

File: packages/style-loader/index.js [hunk 1]
```diff
@@ -44,9 +44,9 @@ module.exports = (neutrino, opts = {}) => {
         test: options.modulesTest,
         exclude: options.modulesExclude,
         ruleId: `${options.ruleId}${options.modulesSuffix}`,
-        styleUseId: `${options.styleUseId}${options.modulesSuffix}`,
-        cssUseId: `${options.cssUseId}${options.modulesSuffix}`,
-        extractId: `${options.extractId}${options.modulesSuffix}`,
+        styleUseId: `${options.styleUseId}`,
```
Comment (eliperelman) [inline packages/style-loader/index.js]: These don't need to be wrapped in template strings I think.

Comment (timkelty) [reply packages/style-loader/index.js]: In fact, they don't need to be there at all, now that the ids are the same…

**Comment by timkelty** [comment]
Once https://github.com/neutrinojs/neutrino/pull/1281 is merged and https://github.com/neutrinojs/webpack-chain/pull/133 is release, I can rebase this PR and it should be good to go, bump the webpack-chain dep, and should be good to go.

**Comment by timkelty** [comment]
Ok @edmorley, I've rebased this off `master` following the merge of https://github.com/neutrinojs/neutrino/pull/1281. Now all we're waiting on is a published version of webpack-chain with https://github.com/neutrinojs/webpack-chain/pull/133

**Comment by edmorley** [comment]
Thank you for rebasing. The new version of webpack-chain was released yesterday:
https://github.com/neutrinojs/webpack-chain/pull/133#issuecomment-454759300

**Comment by timkelty** [comment]
Doh, missed that! I'll change that and do some final tests now.

**Comment by edmorley** [comment]
Travis is failing in the create-project test matrix. Perhaps it would be useful to have an additional test that verifies the output of `.toConfig()` so we can confirm the nested rules are laid out as expected?

**Comment by timkelty** [comment]
@edmorley investigating. Initially this was the problem: https://github.com/neutrinojs/webpack-chain/issues/140, but I'm now using `.values()`

**Comment by timkelty** [comment]
Ok @edmorley , Travis should be happy now.
I revised the test as well.
